version: '3.9'

services:
  # Dolibarr
  dolibarr:
    image: tuxgasy/dolibarr:14.0.2
    container_name: dolibarr
    ports:
      - "80:80"
    environment:
      - DOLI_DB_HOST=dolibarr-mariadb
      - DOLI_DB_USER=epitech
      - DOLI_DB_PASSWORD=epitech13
      - DOLI_DB_NAME=dolibarr
    links:
      - dolibarr-mariadb
#password admin admin
  # MariaDB
  dolibarr-mariadb:
    image: mariadb:10.8
    container_name: dolibarr-mariadb
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=epitech13
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=epitech
      - MYSQL_PASSWORD=epitech13

  # PHPMyAdmin
  dolibarr-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dolibarr-phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=dolibarr-mariadb
      - PMA_PORT=3306
      - PMA_USER=epitech
      - PMA_PASSWORD=epitech13

volumes:
  data: